---
title: "Acute Pain Management in the Perioperative Setting (2012)"
editor: source
toc-title: "**Acute Pain Management (2012)**"
toc-location: "right"
cap-location: "top"
toc-depth: 3
page-layout: full
css: styles.css
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
---

The complete guideline can be found [here.](https://pubs.asahq.org/anesthesiology/article/116/2/248/12956/Practice-Guidelines-for-Acute-Pain-Management-in)

## Recommendations

```{r recommendations}
#| echo: false
source("preliminary.R")
#| echo: false
recs_dat <- readxl::read_xlsx("_data/pp_recs_all.xlsx", sheet = "Guidelines", range = "A1:F485") |> 
  filter(str_detect(parameter, "Acute Pain")) |> 
  mutate(
    evidence = str_replace(evidence, "Consensus statement", " — "),
    rec = str_replace(rec, "^They", "[Anesthesiologists]")
  )

# sections <- recs_dat |>
#   select(rec_title) |> 
#   distinct()

recs_dat |> 
  select(rec, rec_title, evidence) |> 
  group_by(rec_title) |> 
  gt(id = "one") |> 
  fmt_markdown(columns = c(rec)) |> 
  cols_label(
    rec              = "Recommendation",
    evidence         = md("Strength <br/>of Evidence")
  ) |> 
  cols_width(
    rec              ~ px(600),
    evidence         ~ px(110)
  ) |> 
  tab_style(style = cell_text(align = "center"),      locations = cells_column_labels(columns = everything())) |>
  tab_style(style = cell_text(align = "center"),      locations = cells_body(columns = c(evidence))) |>
  gt_theme_mg() |> 
  opt_stylize(style = 6, color = "blue", add_row_striping = TRUE) |> 
  tab_footnote("— : Recommendation/explanatory without strength of evidence rating.")

```

## Evidence Rating Scheme

***Category A: Supportive Literature***<br/> 
Randomized controlled trials report statistically significant (P \< 0.01) differences between clinical interventions for a specified clinical outcome.<br/>
*Level 1*: The literature contains multiple RCTs, and aggregated findings are supported by meta-analysis.<br/>
*Level 2*: The literature contains multiple RCTs, but the number of studies is insufficient to conduct a viable meta-analysis for the purpose of the Guidelines.<br/>
*Level 3*: The literature contains a single randomized controlled trial.

***Category B: Suggestive Literature*** <br/>
Information from observational studies permits inference of beneficial or harmful relationships among clinical interventions and clinical outcomes.<br/>
*Level 1*: The literature contains observational comparisons (e.g., cohort, case-control research designs) of clinical interventions or conditions and indicates statistically significant differences between clinical interventions for a specified clinical outcome.<br/>
*Level 2*: The literature contains noncomparative observational studies with associative (e.g., relative risk, correlation) or descriptive statistics.<br/>
*Level 3*: The literature contains case reports.

***Category C: Equivocal Literature***<br/> 
The literature cannot determine whether there are beneficial or harmful relationships among clinical interventions and clinical outcomes.<br/>
*Level 1*: Meta-analysis did not find significant differences (P \> 0.01) among groups or conditions.<br/>
*Level 2*: The number of studies is insufficient to conduct meta-analysis, and (1) RCTs have not found significant differences among groups or conditions or (2) RCTs report inconsistent findings.<br/>
*Level 3*: Observational studies report inconsistent findings or do not permit inference of beneficial or harmful relationships.<br/>

***Category D: Insufficient Evidence from Literature*** <br/>
The lack of scientific evidence in the literature is described by the following terms.

***Inadequate:*** The available literature cannot be used to assess relationships among clinical interventions and clinical outcomes. The literature either does not meet the criteria for content as defined in the "Focus" of the Guidelines or does not permit a clear interpretation of findings due to methodological concerns (e.g., confounding in study design or implementation).

***Silent:*** No identified studies address the specified relationships among interventions and outcomes.

