---
title: "Management of the Difficult Airway (2013)"
editor: source
toc-title: "**Difficult Airway (2013)**"
toc-location: "right"
cap-location: "top"
toc-depth: 3
page-layout: full
css: styles.css
tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "
---

The complete guideline can be found [here.](https://pubs.asahq.org/anesthesiology/article/118/2/251/13535/Practice-Guidelines-for-Management-of-the)

## Recommendations

```{r recommendations}
#| echo: false
source("preliminary.R")
recs_dat <- recs_all_dat |>  
  filter(str_detect(parameter, "Difficult Airway")) |> 
  mutate(
    evidence = str_replace(evidence, "Consensus statement", " — "),
    rec = str_replace(rec, "^They", "[Anesthesiologists]")
  )

# sections <- recs_dat |>
#   select(rec_title) |> 
#   distinct()

recs_function() |> 
  tab_footnote("— : Recommendation/explanatory without strength of evidence rating.")

```

## Evidence Rating Scheme

***Category A***<br/>
RCTs report comparative findings between clinical interventions for specified outcomes. Statistically significant (P < 0.01) outcomes are designated as either beneficial (B) or harmful (H) for the patient; statistically nonsignificant findings are designated as equivocal (E).<br/>
*Level 1:* The literature contains a sufficient number of RCTs to conduct meta-analysis, and meta-analytic findings from these aggregated studies are reported as evidence.<br/>
*Level 2:* The literature contains multiple RCTs, but the number of RCTs is not sufficient to conduct a viable meta-analysis for the purpose of these updated guidelines. Findings from these RCTs are reported separately as evidence.<br/>
*Level 3:* The literature contains a single RCT, and findings are reported as evidence.

***Category B.***<br/>
Observational studies or RCTs without pertinent comparison groups may permit inference of beneficial or harmful relationships among clinical interventions and clinical outcomes. Inferred findings are given a directional designation of beneficial (B), harmful (H), or equivocal (E). For studies that report statistical findings, the threshold for significance is P < 0.01.<br/>
*Level 1:* The literature contains observational comparisons (e.g., cohort, case-control research designs) with comparative statistics between clinical interventions for a specified clinical outcome.<br/>
*Level 2:* The literature contains noncomparative observational studies with associative statistics (e.g., relative risk, correlation, sensitivity/specificity).<br/>
*Level 3:* The literature contains noncomparative observational studies with descriptive statistics (e.g., frequencies, percentages).<br/>
*Level 4:* The literature contains case reports.

***Insufficient Literature.***<br/>
The lack of sufficient scientific evidence in the literature may occur when the evidence is either unavailable (i.e., no pertinent studies found) or inadequate. Inadequate literature cannot be used to assess relationships among clinical interventions and outcomes because a clear interpretation of findings is not obtained due to methodological concerns (e.g., confounding of study design or implementation), or the study does not meet the criteria for content as defined in the “Focus” of the guidelines.

