project:
  type: book
  output-dir: docs

book:
  title: "Practice Parameter Recommendations"
  author: ""
  date: "2023-07-28"
  chapters:
    - index.qmd
    - 2023_nmb.qmd
    - 2023_fasting.qmd
    - 2016_obstetrics_anesthesia.qmd
    - 2015_blood_management.qmd
    - 2015_neuraxial_opioid.qmd
    - 2013_difficult_airway.qmd
    - 2012_central_venous_access.qmd
    - 2012_pain.qmd
    - 2010_chronic_pain.qmd
    # - summary.qmd
    - references.qmd
  search:
    location: navbar
    type: textbox
    limit: 40

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

