project:
  type: book
  output-dir: docs

book:
  title: "Practice Parameter Recommendations"
  author: ""
  date: "5/24/2022"
  chapters:
    - index.qmd
    - 2012_pain.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

